name: stacktrace_impl
version: 2.3.0
homepage: https://github.com/bsutton/stacktrace_impl
description: Allows you to instantiate a StackTrace and provides logging control.
environment: 
  sdk: '>=2.18.0 <3.0.0'
dependencies: 
  path: ^1.8.0
dev_dependencies: 
  lint_hard: ^2.0.0
  test: ^1.19.5
